### ISSUE TITLE
Tagging releases

### ISSUE THREAD

**Issue by achew22** [rhysbrettbowen/PlastronJS#16]
Is there any way you could tag your releases so that it can be used as a git submodule?

Thank you very much!

**Comment by rhysbrettbowen** [comment]
I haven't done much with git other than just upload things but will look in to it

**Comment by achew22** [comment]
Thank you very much. When I tag things, this is the reference I use.

http://git-scm.com/book/en/Git-Basics-Tagging

**Comment by rhysbrettbowen** [comment]
tags should start coming in, I've tagged v1.0.4 and v1.0.5 so far

**Comment by achew22** [comment]
Rhys, did you push the tags up to GitHub? I can't see them up here

**Comment by rhysbrettbowen** [comment]
I thought I had - maybe the tags don't push through. I'll have to have a look in to it

**Comment by rhysbrettbowen** [comment]
needed to do "git push --tags"

let me know if you still can't see them

**Comment by achew22** [comment]
Hurray! Btw, this means you now have a directly linkable zip/tar.gz file for every commit that you tag. if you want to include links to download at those tags (like in documentation or in an announcement to a newsgroup), they are at https://github.com/rhysbrettbowen/PlastronJS/tags
