### ISSUE TITLE
Setting value fails with setter on complex field.

### ISSUE THREAD

**Issue by kozerskil** [rhysbrettbowen/PlastronJS#19]
In my model I have object with some field. I can use it like:

model.set('customer.name', 'John')

and this creates {'customer':{'name':'John'}} in my model.

If I register setter:

model.setter('customer.name', function(name) {
  return name;
})

then this

model.set('customer.name', 'John')

creates {'customer.name':'John'} in my model.

**Comment by rhysbrettbowen** [comment]
latest commit 6dacb6a8d2bf3113fdae6df15638108ff400bc21 should fix it, let me know if it doesn't
