### ISSUE TITLE
route executed twice

### ISSUE THREAD

**Issue by gmkumar2005** [rhysbrettbowen/PlastronJS#2]
I have a goog.ui.filtermenu in my application. When a user clicks a menu item , the window.location.hash is set to the caption of the menuitem (say #User).  The router executes an event handler to paint the screen.  

``` javascript
router.route(token, function(id) 
```

User can navigate to #User without clicking. In such case the route executes the event handler which will restore the state of the screen.

The issue is route in above code executes twice. Once due to PopState and again for HashChangeEvent. 
Is there a way to avoid double execution of the route. The double execution happens in both cases ie, a) user clicks menu b) user navigates to #User

I have tried  e.stopPropagation(); inside the eventHandler for filterMenu 
Is there a way to avoid double execution 
Below are the two stack traces 
bs.controllers.menuControl.toggleChecked (menuControl.js:75)
(anonymous function) (app.js:75)
(anonymous function) (router.js:73)
goog.array.forEach (array.js:178)
mvc.Router.onChange_ (router.js:69)
goog.events.Listener.handleEvent (listener.js:157)
goog.events.fireListener (events.js:777)
goog.events.fireListeners_ (events.js:756)
goog.events.dispatchEvent (events.js:880)
goog.events.EventTarget.dispatchEvent (eventtarget.js:181)
goog.history.Html5History.onHistoryEvent_ (html5history.js:255)
goog.events.Listener.handleEvent (listener.js:157)
goog.events.fireListener (events.js:777)
goog.events.handleBrowserEvent_ (events.js:1009)
(anonymous function) (events.js:250)
bs.controllers.menuControl.checkedHandler (menuControl.js:164)
goog.events.Listener.handleEvent (listener.js:157)
goog.events.fireListener (events.js:777)
goog.events.fireListeners_ (events.js:756)
goog.events.dispatchEvent (events.js:850)
goog.events.EventTarget.dispatchEvent (eventtarget.js:181)
goog.ui.Control.isTransitionAllowed (control.js:1125)
goog.ui.Control.setChecked (control.js:906)
goog.ui.Control.performActionInternal (control.js:1275)
goog.ui.Control.handleMouseUp (control.js:1236)
goog.base (base.js:1507)
goog.ui.MenuItem.handleMouseUp (menuitem.js:196)
goog.ui.Container.handleChildMouseEvents (container.js:611)
goog.events.Listener.handleEvent (listener.js:157)
goog.events.fireListener (events.js:777)
goog.events.handleBrowserEvent_ (events.js:1009)
(anonymous function) (events.js:250)

+++++++++Second trace+++++++++++
bs.controllers.menuControl.toggleChecked (menuControl.js:75)
(anonymous function) (app.js:75)
(anonymous function) (router.js:73)
goog.array.forEach (array.js:178)
mvc.Router.onChange_ (router.js:69)
goog.events.Listener.handleEvent (listener.js:157)
goog.events.fireListener (events.js:777)
goog.events.fireListeners_ (events.js:756)
goog.events.dispatchEvent (events.js:880)
goog.events.EventTarget.dispatchEvent (eventtarget.js:181)
goog.history.Html5History.onHistoryEvent_ (html5history.js:255)
goog.events.Listener.handleEvent (listener.js:157)
goog.events.fireListener (events.js:777)
goog.events.handleBrowserEvent_ (events.js:1009)
(anonymous function) (events.js:250)

Thanks
Kiran

**Comment by rhysbrettbowen** [comment]
looks like there are two different events. This is the trickiest thing to do in an evented system is to pass off the immediate execution and instead wait for events. So the menu item should only set the state and the callback should only listen to the state (not to the menu item as well)

if your callback is only listening to the route and you make the menu item only change the route these will be your two cases:

click menu -> sets route -> route event -> callback

or

user navigates to url -> route event -> callback

the trick is to separate that callback in to parts. So when a user clicks a menu item then your callback should only set the route and the callback on the route should update the menuItem.

I usually like to have the mediator announce changes to the route, and you could have a callback on that which would set the proper UI for the menuItem see: http://modernjavascript.blogspot.com/2012/06/routing-and-state.html

**Comment by gmkumar2005** [comment]
Problem is solved by using 
var router = new mvc.Router(false); which means fragment is visible in the url. Not sure why it does not work with new mvc.Router(true). Actually i don't understand how the html5 feature of hide_fragment works so i am ignoring.
For now it is good enough for me.
