### ISSUE TITLE
Issue with newest closure library

### ISSUE THREAD

**Issue by kozerskil** [rhysbrettbowen/PlastronJS#20]
After updating closure library I have an error:
Uncaught AssertionError: Assertion failed: Event target is not initialized. Did you call superclass (goog.events.EventTarget) constructor? 

on line 
goog.events.listen(this.router, mvc.Router.EventType.ROUTE_EXPIRED, this.expire_, false, this);

I think there is same thing with model.

Solution: both of them should call super constructor.

**Comment by rhysbrettbowen** [comment]
You're right, I've added in goog.base(this) for both Router and Model and updated the tag to v1.0.7
